name: CI/CD

on:
  push:
    branches:
      - '**'    # すべてのブランチでトリガー
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        run: |
          echo "ここでビルドやテスト"

  deploy:
    if: github.ref == 'refs/heads/main'  # 本番デプロイは main ブランチだけ
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-run-github-actions-sample \
            --source ./sample-app \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --build-service-account projects/invox-tech-assignment/serviceAccounts/${{ secrets.GCP_SERVICE_ACCOUNT }}
