name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # checkout 用
      id-token: write   # OIDC 用

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # 2. Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093' # v3.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # 3. Deploy to Cloud Run using Buildpacks
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-run-github-actions-sample \
            --source ./apps/proxy-api-for-open-ai \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --set-env-vars=API_KEY=${{ secrets.API_KEY }}
            --set-env-vars=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
