name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read    # checkout 用
      id-token: write   # OIDC 用

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Authenticate to GCP using Workload Identity Federation
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # 3. Deploy to Cloud Run using Buildpacks
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-run-github-actions-sample \
            --source ./sample-app \
            --region asia-northeast1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --build-service-account projects/invox-tech-assignment/serviceAccounts/${{ secrets.GCP_SERVICE_ACCOUNT }}